### ISSUE TITLE
Doubts about pre-trained models

### ISSUE THREAD

**Issue by 980202006** [csteinmetz1/steerable-nafx#5]
Hello, can you provide the parameter settings for pt model training such as compressor_full.pt, and the data used?

**Comment by csteinmetz1** [comment]
You can find the parameter settings in Table 1 on page of the [paper](https://arxiv.org/abs/2112.02926).

You can reproduce all these results in the [colab notebook](https://colab.research.google.com/github/csteinmetz1/steerable-nafx/blob/master/steerable-nafx.ipynb). 

In the notebook the audio files needed are downloaded. For example, you can download the compressor training data which is just two files.
```
wget https://csteinmetz1.github.io/sounds/assets/drum_kit_clean.wav 
wget https://csteinmetz1.github.io/sounds/assets/drum_kit_comp_agg.wav 
```

**Comment by 980202006** [comment]
Thank you!
